apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyaml
    environment : josh
  name: podyaml
spec:
  containers:
  - image: nginx
    name: podyaml
    volumeMounts:
      - mountPath: "/scrath"
        name: my-volume
    resources: {}
  volumes:
    - name: my-volume
      emptyDir:
        sizeLimit: 50Mi
  dnsPolicy: ClusterFirst
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}