apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyam
    environment : josh
  name: podyam
spec:
  containers:
  - image: josh
    name: podyam
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}